plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' version '1.9.22' apply false
}

android {
    compileSdk 34

    defaultConfig {
        applicationId "com.chavesgu.scan_example"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.22"
}

